# Generated by Django 5.2.2 on 2025-06-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_muscle', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], default='Chest', max_length=100)),
                ('equipment', models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Cable', 'Cable'), ('Bodyweight', 'Bodyweight'), ('Kettlebell', 'Kettlebell'), ('Other', 'Other')], default='Barbell', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_dashboard.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('rest_timer', models.CharField(default='00:00', max_length=10)),
                ('template_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_sets_template', to='templates_dashboard.workoutexercisetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercisetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises_template', to='templates_dashboard.workouttemplate'),
        ),
    ]
