# Generated by Django 5.2.2 on 2025-06-19 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_sets', to='workout.workoutexercise')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutSet',
        ),
    ]
