# Generated by Django 5.2.2 on 2025-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_templates', '0002_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout_template',
            new_name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
    ]
