# Generated by Django 5.2.2 on 2025-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_templates', '0003_rename_workout_template_exercise_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], default='Chest', max_length=100),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='workout_templates.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=3),
        ),
    ]
