# Generated by Django 5.2.2 on 2025-06-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_templates', '0005_workouttemplate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='exercises',
        ),
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_templates.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='workout_templates.workouttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('rest_timer', models.CharField(default='00:00', max_length=10)),
                ('template_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout_templates.templateexercise')),
            ],
        ),
    ]
