# Generated by Django 5.2.2 on 2025-06-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_templates', '0007_workout_workoutexercise_workoutset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='workout_exercise',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutSet',
        ),
    ]
