# Generated by Django 5.2.2 on 2025-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_templates', '0009_remove_templateexercise_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Cable', 'Cable'), ('Bodyweight', 'Bodyweight'), ('Kettlebell', 'Kettlebell'), ('Other', 'Other')], default='Barbell', max_length=50),
        ),
    ]
