# Generated by Django 5.2.2 on 2025-06-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('workout_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workouttemplate')),
            ],
        ),
    ]
